// Render smoke tests for the three kit demos generated by formstand-cli
// from the Onboarding schema — the SAME schema and chrome as the mui
// module demo, with only --ui varying. The files are committed UNTOUCHED —
// regenerate them (from the repo root, after `npm --prefix cli run build`)
// via scripts/generate-cli-demos.mjs instead of editing; CI diffs the
// output.
//
// Each demo is single-file layout (useForm inside the component), so there
// is no module singleton to reset — every render is a fresh form. The
// chakra and mantine outputs assume the host mounts their provider (same
// policy as the generated code documents), so the tests wrap them exactly
// as the playground's bridges do; antd needs no provider.
import { ChakraProvider, defaultSystem } from "@chakra-ui/react";
import { MantineProvider } from "@mantine/core";
import { fireEvent, render, screen } from "@testing-library/react";
import { StrictMode, type ReactElement } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AntdOnboardingForm } from "../../examples/src/generated/AntdOnboardingForm";
import { ChakraOnboardingForm } from "../../examples/src/generated/ChakraOnboardingForm";
import { MantineOnboardingForm } from "../../examples/src/generated/MantineOnboardingForm";

// Any console.error — a React key warning, a controlled/uncontrolled flip,
// an act() violation — is a generated-output bug; fail loudly on it.
beforeEach(() => {
  vi.spyOn(console, "error").mockImplementation(() => {});
});

afterEach(() => {
  vi.restoreAllMocks();
});

const SECTION_TITLES = [
  "Personal",
  "Address",
  "Employment",
  "Equipment",
  "Emergency Contacts",
] as const;

// The shared per-kit assertions: the whole point of these demos is that
// the SAME schema renders the same form shape through every backend, so
// the smoke test is one spec run three times.
const expectOnboardingForm = (ui: ReactElement): void => {
  render(<StrictMode>{ui}</StrictMode>);

  expect(screen.getByRole("button", { name: "Submit" })).toBeDefined();
  SECTION_TITLES.forEach((title) => {
    expect(screen.getByText(title)).toBeDefined();
  });

  // Text binding: every kit associates its label with the control (chakra
  // via Field context, mantine via its label prop, antd via htmlFor/id).
  const firstName = screen.getByLabelText("First Name") as HTMLInputElement;
  fireEvent.change(firstName, { target: { value: "Ada" } });
  expect(firstName.value).toBe("Ada");

  // Array binding: the generated add/remove drives useFieldArray. "Name"
  // is an exact-match query, so it cannot collide with "First Name".
  expect(screen.queryAllByLabelText("Name")).toHaveLength(0);
  const add = screen.getByRole("button", { name: "Add emergency contacts" });
  fireEvent.click(add);
  fireEvent.click(add);
  expect(screen.getAllByLabelText("Name")).toHaveLength(2);

  fireEvent.click(screen.getAllByRole("button", { name: "Remove" })[0] as HTMLElement);
  expect(screen.getAllByLabelText("Name")).toHaveLength(1);

  expect(console.error).not.toHaveBeenCalled();
};

describe("generated kit demos (untouched single-file output, one schema, three --ui backends)", () => {
  it("renders the Onboarding schema through --ui chakra", () => {
    expectOnboardingForm(
      <ChakraProvider value={defaultSystem}>
        <ChakraOnboardingForm />
      </ChakraProvider>,
    );
  });

  it("renders the Onboarding schema through --ui mantine", () => {
    expectOnboardingForm(
      <MantineProvider>
        <MantineOnboardingForm />
      </MantineProvider>,
    );
  });

  it("renders the Onboarding schema through --ui antd", () => {
    expectOnboardingForm(<AntdOnboardingForm />);
  });
});
