// Render smoke test for the boundary-testing forms generated by
// formstand-cli from examples/src/generated/boundarySchemas.ts. The
// generated files are committed UNTOUCHED — regenerate them (from the repo
// root, after `npm --prefix cli run build`) instead of editing:
//
//   node cli/dist/cli.js examples/src/generated/boundarySchemas.ts --export kitchenSinkSchema --name KitchenSinkForm --layout module --out examples/src/generated/KitchenSinkForm --force
//   node cli/dist/cli.js examples/src/generated/boundarySchemas.ts --export deepBoundarySchema --name DeepBoundaryForm --out examples/src/generated/DeepBoundaryForm.tsx --force
//   node cli/dist/cli.js examples/src/generated/boundarySchemas.ts --export nestedArrayStressSchema --name NestedArrayStressForm --layout module --out examples/src/generated/NestedArrayStressForm --force
//
// (scripts/generate-cli-demos.mjs runs all three; CI diffs the output.)
//
// DeepBoundaryForm.tsx is NOT rendered here and NOT wired as a playground
// demo: the CLI's default --max-depth (10) emits 9-segment paths
// ("l1.l2.l3.l4.l5.l6.l7.l8.leaf"), past formstand's FieldPath type budget
// of 7 segments (src/core/fieldPath.ts), so importing the file into any
// typechecked program fails with TS2820. The untouched output is kept on
// disk (excluded in examples/tsconfig.json) as the reproduction; render it
// here once the CLI clamps its depth budget to the library's.
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { StrictMode } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  KitchenSinkForm,
  kitchenSinkForm,
} from "../../examples/src/generated/KitchenSinkForm";
import {
  NestedArrayStressForm,
  nestedArrayStressForm,
} from "../../examples/src/generated/NestedArrayStressForm";

// Any console.error — a React key warning, a controlled/uncontrolled flip,
// an act() violation — is a generated-output bug; fail loudly on it.
const spyOnConsoleError = () =>
  vi.spyOn(console, "error").mockImplementation(() => {});

beforeEach(spyOnConsoleError);

// The module layout's forms are module singletons (createForm at module
// scope), so their state survives unmounts — reset them between tests to
// keep each case independent.
afterEach(() => {
  cleanup();
  kitchenSinkForm.reset();
  nestedArrayStressForm.reset();
  vi.restoreAllMocks();
});

const rows = (legendPrefix: string): readonly HTMLElement[] =>
  screen.queryAllByRole("group", {
    name: new RegExp(`^${legendPrefix} #`),
  });

const clickAdd = (name: string, times: number): void => {
  // Re-query each click: adding a row re-renders the section.
  Array.from({ length: times }).forEach(() => {
    fireEvent.click(screen.getAllByRole("button", { name })[0] as HTMLElement);
  });
};

describe("generated KitchenSinkForm (untouched --layout module output)", () => {
  it("mounts with a submit button and every section", () => {
    render(
      <StrictMode>
        <KitchenSinkForm />
      </StrictMode>,
    );
    expect(screen.getByRole("button", { name: "Submit" })).toBeDefined();
    // One fieldset per top-level object/array/tuple section.
    ["Contact", "Coordinates", "Aliases", "Projects"].forEach((legend) => {
      expect(
        screen.getByRole("group", { name: new RegExp(`^${legend}`) }),
      ).toBeDefined();
    });
    expect(console.error).not.toHaveBeenCalled();
  });

  it("adds and removes primitive array rows (aliases) without warnings", () => {
    render(
      <StrictMode>
        <KitchenSinkForm />
      </StrictMode>,
    );
    expect(rows("Aliases")).toHaveLength(0);

    clickAdd("Add aliases", 3);
    expect(rows("Aliases")).toHaveLength(3);

    const firstRemove = rows("Aliases")[0]?.querySelector("button");
    expect(firstRemove?.textContent).toContain("Remove");
    fireEvent.click(firstRemove as HTMLButtonElement);
    expect(rows("Aliases")).toHaveLength(2);
    expect(console.error).not.toHaveBeenCalled();
  });

  it("adds object rows (projects) and their nested tag rows", () => {
    render(
      <StrictMode>
        <KitchenSinkForm />
      </StrictMode>,
    );
    clickAdd("Add projects", 2);
    expect(rows("Projects")).toHaveLength(2);

    // Each project row extracts its own tags array component.
    expect(screen.getAllByRole("button", { name: "Add tags" })).toHaveLength(
      2,
    );
    clickAdd("Add tags", 2);
    expect(rows("Tags")).toHaveLength(2);
    expect(console.error).not.toHaveBeenCalled();
  });
});

describe("generated NestedArrayStressForm (untouched --layout module output)", () => {
  it("mounts with a submit button and both array sections", () => {
    render(
      <StrictMode>
        <NestedArrayStressForm />
      </StrictMode>,
    );
    expect(screen.getByRole("button", { name: "Submit" })).toBeDefined();
    expect(screen.getByRole("group", { name: /^Teams/ })).toBeDefined();
    expect(
      screen.getByRole("group", { name: /^Duplicate Tags/ }),
    ).toBeDefined();
    expect(console.error).not.toHaveBeenCalled();
  });

  it("drives all three array levels (teams › members › phones)", () => {
    render(
      <StrictMode>
        <NestedArrayStressForm />
      </StrictMode>,
    );
    clickAdd("Add teams", 2);
    expect(rows("Teams")).toHaveLength(2);

    // One members array per team row; fill the first team.
    expect(
      screen.getAllByRole("button", { name: "Add members" }),
    ).toHaveLength(2);
    clickAdd("Add members", 2);
    expect(rows("Members")).toHaveLength(2);

    // One phones array per member row; fill the first member.
    expect(
      screen.getAllByRole("button", { name: "Add phones" }),
    ).toHaveLength(2);
    clickAdd("Add phones", 3);
    expect(rows("Phones")).toHaveLength(3);

    // Removing a phone touches only the innermost level.
    const phoneRemove = rows("Phones")[0]?.querySelector("button");
    fireEvent.click(phoneRemove as HTMLButtonElement);
    expect(rows("Phones")).toHaveLength(2);
    expect(rows("Members")).toHaveLength(2);
    expect(rows("Teams")).toHaveLength(2);

    // Removing the first team drops its members (and their phones) with it.
    // The team's own Remove renders after its nested arrays, so it is the
    // LAST "Remove" inside the team fieldset (the first ones belong to the
    // phone/member rows).
    const teamRemove = Array.from(
      (rows("Teams")[0] as HTMLElement).querySelectorAll("button"),
    )
      .filter((button) => button.textContent === "Remove")
      .at(-1);
    fireEvent.click(teamRemove as HTMLButtonElement);
    expect(rows("Teams")).toHaveLength(1);
    expect(rows("Members")).toHaveLength(0);
    expect(rows("Phones")).toHaveLength(0);
    expect(console.error).not.toHaveBeenCalled();
  });

  it("keeps duplicate-prone primitive rows keyed apart", () => {
    render(
      <StrictMode>
        <NestedArrayStressForm />
      </StrictMode>,
    );
    // Every row holds the identical value ("") — distinct row ids are the
    // only thing standing between this and a React duplicate-key warning.
    clickAdd("Add duplicate tags", 4);
    expect(rows("Duplicate Tags")).toHaveLength(4);

    const removeSecond = rows("Duplicate Tags")[1]?.querySelector("button");
    fireEvent.click(removeSecond as HTMLButtonElement);
    expect(rows("Duplicate Tags")).toHaveLength(3);
    expect(console.error).not.toHaveBeenCalled();
  });
});

describe("generated DeepBoundaryForm (known failure, not rendered)", () => {
  it("keeps the untouched reproduction on disk", () => {
    // The file cannot be imported (TS2820: "l1.l2.l3.l4.l5.l6.l7.l8.leaf"
    // is not assignable to formstand's FieldPath union, which stops at 7
    // segments) — assert the evidence stays checked in until the CLI bug
    // is fixed and the form gets rendered here like the other two.
    // Vitest runs from the repo root.
    const file = join(
      process.cwd(),
      "examples/src/generated/DeepBoundaryForm.tsx",
    );
    expect(existsSync(file)).toBe(true);
  });
});
