// Render smoke tests for the three kit demos generated by formstand-cli
// from the Onboarding schema — the SAME schema and chrome as the mui
// module demo, with only --ui varying. The files are committed UNTOUCHED —
// regenerate them (from the repo root, after `npm --prefix cli run build`)
// via scripts/generate-cli-demos.mjs instead of editing; CI diffs the
// output.
//
// Each demo is single-file layout (useForm inside the component), so there
// is no module singleton to reset — every render is a fresh form. The
// chakra and mantine outputs assume the host mounts their provider (same
// policy as the generated code documents), so the tests wrap them exactly
// as the playground's bridges do; antd needs no provider. The mui MODULE
// demo (the fourth backend, --layout module) joins the number-typing and
// array-error runs below — it IS a module singleton (createForm at module
// scope), so it gets reset between tests; MUI needs no provider either.
import { ChakraProvider, defaultSystem } from "@chakra-ui/react";
import { MantineProvider } from "@mantine/core";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { StrictMode, type ReactElement } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { focusField } from "../../src/react/focusError";
import { AntdOnboardingForm } from "../../examples/src/generated/AntdOnboardingForm";
import { ChakraOnboardingForm } from "../../examples/src/generated/ChakraOnboardingForm";
import { MantineOnboardingForm } from "../../examples/src/generated/MantineOnboardingForm";
import {
  OnboardingForm,
  onboardingForm,
} from "../../examples/src/generated/OnboardingForm";

// Any console.error — a React key warning, a controlled/uncontrolled flip,
// an act() violation — is a generated-output bug; fail loudly on it.
beforeEach(() => {
  vi.spyOn(console, "error").mockImplementation(() => {});
});

afterEach(() => {
  cleanup();
  onboardingForm.reset();
  vi.restoreAllMocks();
});

const SECTION_TITLES = [
  "Personal",
  "Address",
  "Employment",
  "Equipment",
  "Emergency Contacts",
] as const;

// The shared per-kit assertions: the whole point of these demos is that
// the SAME schema renders the same form shape through every backend, so
// the smoke test is one spec run three times.
const expectOnboardingForm = (ui: ReactElement): void => {
  render(<StrictMode>{ui}</StrictMode>);

  expect(screen.getByRole("button", { name: "Submit" })).toBeDefined();
  SECTION_TITLES.forEach((title) => {
    expect(screen.getByText(title)).toBeDefined();
  });

  // Text binding: every kit associates its label with the control (chakra
  // via Field context, mantine via its label prop, antd via htmlFor/id).
  const firstName = screen.getByLabelText("First Name") as HTMLInputElement;
  fireEvent.change(firstName, { target: { value: "Ada" } });
  expect(firstName.value).toBe("Ada");

  // Array binding: the generated add/remove drives useFieldArray. "Name"
  // is an exact-match query, so it cannot collide with "First Name".
  expect(screen.queryAllByLabelText("Name")).toHaveLength(0);
  const add = screen.getByRole("button", { name: "Add emergency contacts" });
  fireEvent.click(add);
  fireEvent.click(add);
  expect(screen.getAllByLabelText("Name")).toHaveLength(2);

  fireEvent.click(screen.getAllByRole("button", { name: "Remove" })[0] as HTMLElement);
  expect(screen.getAllByLabelText("Name")).toHaveLength(1);

  expect(console.error).not.toHaveBeenCalled();
};

// Simulates real typing into a controlled input: after each keystroke the
// component re-renders the value, and the next character appends to
// whatever the input then DISPLAYS — exactly how a value-reparsing binding
// corrupts entries ("85000.50" → "8500050", "-5" → "5").
const typeChars = (input: HTMLInputElement, text: string): void => {
  text.split("").forEach((char) => {
    fireEvent.change(input, { target: { value: input.value + char } });
  });
};

// The raw-text number-editing contract every kit demo must satisfy (the
// generated useNumberText hook, mirroring the library's useNumberInput):
// intermediate text survives keystroke-by-keystroke, blur snaps to the
// canonical parsed value, and a leading "-" is not eaten.
const expectNumberEditing = (ui: ReactElement): void => {
  render(<StrictMode>{ui}</StrictMode>);
  const salary = screen.getByLabelText("Salary") as HTMLInputElement;

  typeChars(salary, "85000.50");
  expect(salary.value).toBe("85000.50");
  fireEvent.blur(salary);
  expect(salary.value).toBe("85000.5");

  fireEvent.change(salary, { target: { value: "" } });
  typeChars(salary, "-5");
  expect(salary.value).toBe("-5");
  fireEvent.blur(salary);
  expect(salary.value).toBe("-5");

  expect(console.error).not.toHaveBeenCalled();
};

// Submitting the blank form (emergencyContacts starts []) must surface the
// ARRAY-level error (z.array().min(1, "add at least one contact")) — the
// single-file emitters render the hook's .error like the module layout —
// announced via role="alert" in every kit. And the error must not go STALE:
// after the failed submit the revalidate gate is open (submitCount > 0,
// reValidateMode onChange), so adding + filling a contact row clears the
// line through useFieldArray's op revalidation, with no second submit.
const expectArrayLevelError = async (ui: ReactElement): Promise<void> => {
  render(<StrictMode>{ui}</StrictMode>);
  expect(screen.queryByText("add at least one contact")).toBeNull();
  const form = document.querySelector("form");
  expect(form).not.toBeNull();
  fireEvent.submit(form as HTMLFormElement);
  const error = await screen.findByText("add at least one contact");
  expect(error.closest('[role="alert"]')).not.toBeNull();

  fireEvent.click(
    screen.getByRole("button", { name: "Add emergency contacts" }),
  );
  const name = screen.getAllByLabelText("Name")[0] as HTMLInputElement;
  fireEvent.change(name, { target: { value: "Grace" } });
  expect(screen.queryByText("add at least one contact")).toBeNull();
};

describe("generated kit demos (untouched single-file output, one schema, three --ui backends)", () => {
  it("renders the Onboarding schema through --ui chakra", () => {
    expectOnboardingForm(
      <ChakraProvider value={defaultSystem}>
        <ChakraOnboardingForm />
      </ChakraProvider>,
    );
  });

  it("renders the Onboarding schema through --ui mantine", () => {
    expectOnboardingForm(
      <MantineProvider>
        <MantineOnboardingForm />
      </MantineProvider>,
    );
  });

  it("renders the Onboarding schema through --ui antd", () => {
    expectOnboardingForm(<AntdOnboardingForm />);
  });

  it("preserves typed number text through --ui chakra", () => {
    expectNumberEditing(
      <ChakraProvider value={defaultSystem}>
        <ChakraOnboardingForm />
      </ChakraProvider>,
    );
  });

  it("preserves typed number text through --ui mantine", () => {
    expectNumberEditing(
      <MantineProvider>
        <MantineOnboardingForm />
      </MantineProvider>,
    );
  });

  it("preserves typed number text through --ui antd", () => {
    expectNumberEditing(<AntdOnboardingForm />);
  });

  it("shows the array-level error on submit through --ui chakra", async () => {
    await expectArrayLevelError(
      <ChakraProvider value={defaultSystem}>
        <ChakraOnboardingForm />
      </ChakraProvider>,
    );
  });

  it("shows the array-level error on submit through --ui mantine", async () => {
    await expectArrayLevelError(
      <MantineProvider>
        <MantineOnboardingForm />
      </MantineProvider>,
    );
  });

  it("shows the array-level error on submit through --ui antd", async () => {
    await expectArrayLevelError(<AntdOnboardingForm />);
  });

  // The mui MODULE demo (--layout module) must satisfy the same number-
  // editing contract as the single-file kits — its adapter file inlines the
  // same useNumberText hook the single-file emitters embed.
  it("preserves typed number text through the mui module demo", () => {
    expectNumberEditing(<OnboardingForm />);
  });

  it("shows the array-level error on submit through the mui module demo", async () => {
    await expectArrayLevelError(<OnboardingForm />);
  });

  // antd's Select renders no `name` anywhere, so the focus helpers reach it
  // through their [id=path] fallback (the generated markup sets id={path},
  // forwarded to the real combobox input).
  it("focusField reaches the antd Select via the id fallback", () => {
    render(
      <StrictMode>
        <AntdOnboardingForm />
      </StrictMode>,
    );
    expect(focusField("address.region")).toBe(true);
    expect((document.activeElement as HTMLElement).id).toBe("address.region");
  });
});
