import { camelCase, pascalCase } from "./casing";
import {
  type EmitFormOptions,
  type ObjectSpec,
  type SchemaImport,
  assertObjectRoot,
  commentText,
  emitInitialValues,
  identifierSuffix,
  isUnaddressable,
  jsxText,
  q,
  templateEscape,
} from "./codegen";
import { type FieldSpec, type NamedField, labelFromName } from "./ir";

// The --layout module emitter: instead of one file, a feature-module folder
// in the shape of the Onboarding playground demo —
//
//   schema.ts        the zod schema (re-exported in zod mode, generated in
//                    type mode) as the module's single import path for it
//   types.ts         the draft value types
//   hooks.ts         createForm + createFormHooks(form, name): the module's
//                    pre-wired hook API
//   fields/*.tsx     one file per scalar leaf outside arrays — props type,
//                    field hook, component
//   sections/*.tsx   one file per top-level object or array — props type,
//                    section hook (path-scoped dirty/valid flags), component
//   {Name}Form.tsx   the body composing sections and root-level fields
//   index.ts         the folder's public API
//
// Requires formstand >= 0.7 (createFormHooks). Everything is a pure string
// builder over the IR, like the single-file backends.

export type ModuleFile = Readonly<{
  // Forward-slash relative path inside the module folder.
  path: string;
  content: string;
}>;

export type EmitModuleOptions = EmitFormOptions &
  Readonly<{
    // Type mode passes the generated schema source; zod mode omits it and
    // schema.ts re-exports the user's module via schemaImport.from.
    schemaSource?: string;
  }>;

const HEADER = "// Generated by formstand-cli — edit freely, this file is yours.";

// ---------------------------------------------------------------------------
// Naming
// ---------------------------------------------------------------------------

type Naming = Readonly<{
  formName: string; // ProfileForm
  prefix: string; // Profile
  factoryArg: string; // profile
  formConst: string; // profileForm
  valuesType: string; // ProfileValues
  schemaType: string; // ProfileSchema
  hook: (suffix: string) => string; // hook("Field") -> useProfileField
}>;

const namingFor = (formName: string): Naming => {
  const stripped = formName.replace(/Form$/, "");
  const prefix = pascalCase(stripped.length === 0 ? formName : stripped);
  return {
    formName,
    prefix,
    factoryArg: camelCase(prefix),
    formConst: `${camelCase(prefix)}Form`,
    valuesType: `${prefix}Values`,
    schemaType: `${prefix}Schema`,
    hook: (suffix) => `use${prefix}${suffix}`,
  };
};

// ---------------------------------------------------------------------------
// Collection: walk the root once, planning files and section bodies
// ---------------------------------------------------------------------------

type FieldPlan = Readonly<{
  segments: readonly string[];
  componentName: string; // CityField (identifierSuffix-deduped)
  spec: FieldSpec;
  label: string;
}>;

type SectionPlan = Readonly<{
  key: string;
  componentName: string; // AddressSection (deduped)
  label: string;
  spec: ObjectSpec | Extract<FieldSpec, Readonly<{ kind: "array" }>>;
}>;

type Plan = Readonly<{
  fields: readonly FieldPlan[];
  sections: readonly SectionPlan[];
  rootFields: readonly FieldPlan[]; // top-level scalars, rendered in the body
  rootTodos: readonly string[]; // dot-keys etc. surfaced in the body
}>;

const isScalar = (spec: FieldSpec): boolean =>
  spec.kind !== "object" && spec.kind !== "array";

// Scalar leaves under `fields` that are NOT inside an array (array rows bind
// dynamic paths inline in their section file instead).
const collectLeaves = (
  fields: readonly NamedField[],
  segments: readonly string[],
): readonly Readonly<{ segments: readonly string[]; field: NamedField }>[] =>
  fields.flatMap((field) => {
    if (isUnaddressable(field.name)) return [];
    const at = [...segments, field.name];
    switch (field.spec.kind) {
      case "object":
        return collectLeaves(field.spec.fields, at);
      case "array":
        return [];
      default:
        return [{ segments: at, field }];
    }
  });

const buildPlan = (root: ObjectSpec): Plan => {
  const used = new Set<string>();
  const claim = (base: string): string => {
    const name = `${base}${identifierSuffix(base, used)}`;
    used.add(name);
    return name;
  };

  const planField = (
    segments: readonly string[],
    field: NamedField,
  ): FieldPlan => ({
    segments,
    componentName: claim(`${pascalCase(segments[segments.length - 1] ?? "")}Field`),
    spec: field.spec,
    label: field.label,
  });

  const rootFields = root.fields
    .filter((field) => !isUnaddressable(field.name) && isScalar(field.spec))
    .map((field) => planField([field.name], field));

  const sections = root.fields
    .filter(
      (field) =>
        !isUnaddressable(field.name) &&
        (field.spec.kind === "object" || field.spec.kind === "array"),
    )
    .map(
      (field): SectionPlan => ({
        key: field.name,
        componentName: claim(`${pascalCase(field.name)}Section`),
        label: field.label,
        spec: field.spec as SectionPlan["spec"],
      }),
    );

  const sectionLeafFields = sections.flatMap((section) =>
    section.spec.kind === "object"
      ? collectLeaves(section.spec.fields, [section.key]).map(
          ({ segments, field }) => planField(segments, field),
        )
      : [],
  );

  const rootTodos = root.fields
    .filter((field) => isUnaddressable(field.name))
    .map(
      (field) =>
        `{/* TODO: field ${commentText(q(field.name))} skipped — "." in a key is not path-addressable (see formstand docs) */}`,
    );

  return {
    fields: [...rootFields, ...sectionLeafFields],
    sections,
    rootFields,
    rootTodos,
  };
};

// ---------------------------------------------------------------------------
// Leaf rendering (shared by field files and array-row bodies)
// ---------------------------------------------------------------------------

type LeafBinding = Readonly<{
  builder: "textInputProps" | "numberInputProps" | "checkboxProps" | "selectProps";
  extraAttrs: string; // e.g. ` type="date"`
}>;

const leafBinding = (spec: FieldSpec): LeafBinding => {
  switch (spec.kind) {
    case "number":
      return { builder: "numberInputProps", extraAttrs: "" };
    case "boolean":
      return { builder: "checkboxProps", extraAttrs: "" };
    case "enum":
      return { builder: "selectProps", extraAttrs: "" };
    case "date":
      return { builder: "textInputProps", extraAttrs: ` type="date"` };
    default:
      return { builder: "textInputProps", extraAttrs: "" };
  }
};

const todoTexts = (spec: FieldSpec): readonly string[] => [
  ...(spec.todo !== undefined ? [commentText(spec.todo)] : []),
  ...(spec.kind === "date"
    ? [
        "date input — swap in a date picker; this binds a Date-typed field as plain text through a cast",
      ]
    : []),
];

// The control JSX for one leaf bound to `varName` (a useField result held
// in a local), at the given indent. Label-wrapped, so no ids are needed.
const leafJsx = (
  spec: FieldSpec,
  varName: string,
  labelExpr: string,
  indent: string,
): readonly string[] => {
  const { builder, extraAttrs } = leafBinding(spec);
  const control =
    spec.kind === "enum"
      ? [
          `${indent}    <select {...selectProps(${varName})}>`,
          `${indent}      <option value="">{"Select…"}</option>`,
          ...spec.options.map(
            (option) =>
              `${indent}      <option value=${jsxText(option)}>${jsxText(labelFromName(option))}</option>`,
          ),
          `${indent}    </select>`,
        ]
      : [
          `${indent}    <input${extraAttrs} {...${builder}(${varName})} />`,
        ];
  return [
    `${indent}<div>`,
    `${indent}  <label>`,
    `${indent}    ${labelExpr}`,
    ...control,
    `${indent}  </label>`,
    `${indent}  {${varName}.error?.[0] !== undefined ? (`,
    `${indent}    <p role="alert">{${varName}.error?.[0]}</p>`,
    `${indent}  ) : null}`,
    `${indent}</div>`,
  ];
};

// Same, prefixed with JSX-comment TODOs — safe only in child position
// (a comment container can't precede the return expression itself).
const leafControl = (
  spec: FieldSpec,
  varName: string,
  labelExpr: string,
  indent: string,
): readonly string[] => [
  ...todoTexts(spec).map((text) => `${indent}{/* TODO: ${text} */}`),
  ...leafJsx(spec, varName, labelExpr, indent),
];

// Date-typed fields bind a text input, so the hook result is cast to the
// string shape the prop builder takes — flagged by the TODO the file gets.
const isDateBinding = (spec: FieldSpec): boolean => spec.kind === "date";

const DATE_CAST = " as unknown as UseFieldReturn<string | null | undefined>";

const buildersUsed = (specs: readonly FieldSpec[]): readonly string[] => {
  const names = new Set(specs.map((spec) => leafBinding(spec).builder));
  return ["textInputProps", "numberInputProps", "checkboxProps", "selectProps"].filter(
    (name) => names.has(name as LeafBinding["builder"]),
  );
};

// ---------------------------------------------------------------------------
// File emitters
// ---------------------------------------------------------------------------

const schemaFile = (
  schemaImport: SchemaImport,
  schemaSource: string | undefined,
): ModuleFile => ({
  path: "schema.ts",
  content:
    schemaSource !== undefined
      ? `${HEADER}\n${schemaSource}`
      : [
          HEADER,
          "// The schema's source of truth stays where it was; this re-export",
          "// gives every file in the module one import path for it.",
          schemaImport.kind === "default"
            ? `export { default as ${schemaImport.name} } from ${q(schemaImport.from)};`
            : `export { ${schemaImport.name} } from ${q(schemaImport.from)};`,
          "",
        ].join("\n"),
});

const typesFile = (naming: Naming, schemaImport: SchemaImport): ModuleFile => ({
  path: "types.ts",
  content: [
    HEADER,
    `import type { z } from "zod";`,
    `import { ${schemaImport.name} } from "./schema";`,
    "",
    `export type ${naming.schemaType} = typeof ${schemaImport.name};`,
    "",
    "// The draft shape the hooks read and write (z.input: what the form",
    "// holds while being filled, before validation refines it).",
    `export type ${naming.valuesType} = z.input<${naming.schemaType}>;`,
    "",
  ].join("\n"),
});

const hooksFile = (
  naming: Naming,
  schemaImport: SchemaImport,
  root: ObjectSpec,
  plan: Plan,
): ModuleFile => {
  const hasArrays = plan.sections.some((s) => s.spec.kind === "array");
  const hasFields = plan.fields.length > 0 || hasArrays;
  const hooks = [
    ...(hasFields ? [naming.hook("Field")] : []),
    ...(hasArrays ? [naming.hook("FieldArray")] : []),
    ...(plan.sections.length > 0
      ? [naming.hook("IsDirty"), naming.hook("IsValid")]
      : []),
    naming.hook("IsSubmitting"),
  ];
  return {
    path: "hooks.ts",
    content: [
      HEADER,
      `import { createForm, createFormHooks } from "formstand";`,
      `import { ${schemaImport.name} } from "./schema";`,
      `import type { ${naming.valuesType} } from "./types";`,
      "",
      "// A form starts blank: required numbers/dates/enums begin undefined, so",
      "// these initial values intentionally do not satisfy the schema yet —",
      "// hence the cast. Validation reports the gaps on submit.",
      `const initialValues = ${emitInitialValues(root, 0)} as unknown as ${naming.valuesType};`,
      "",
      "// One module-level form for the whole feature; every file below imports",
      "// these pre-wired hooks instead of receiving `form` via props or a",
      "// provider. A module singleton never unmounts — for a per-mount",
      "// lifecycle, use useForm + createFormContext instead.",
      `export const ${naming.formConst} = createForm(${schemaImport.name}, {`,
      "  initialValues,",
      `  mode: "onBlur",`,
      "});",
      "",
      "export const {",
      ...hooks.map((name) => `  ${name},`),
      `} = createFormHooks(${naming.formConst}, ${q(naming.factoryArg)});`,
      "",
    ].join("\n"),
  };
};

const fieldFile = (naming: Naming, field: FieldPlan): ModuleFile => {
  const path = field.segments.join(".");
  const propsType = `${field.componentName}Props`;
  const hookName = `use${field.componentName}`;
  const { builder } = leafBinding(field.spec);
  const dateCast = isDateBinding(field.spec);
  return {
    path: `fields/${field.componentName}.tsx`,
    content: [
      HEADER,
      dateCast
        ? `import { type UseFieldReturn, ${builder} } from "formstand";`
        : `import { ${builder} } from "formstand";`,
      `import { ${naming.hook("Field")} } from "../hooks";`,
      "",
      `export type ${propsType} = Readonly<{ label?: string }>;`,
      "",
      `export const ${hookName} = () => ${naming.hook("Field")}(${q(path)});`,
      "",
      `export const ${field.componentName} = ({`,
      `  label = ${q(field.label)},`,
      `}: ${propsType}) => {`,
      ...todoTexts(field.spec).map((text) => `  // TODO: ${text}`),
      `  const field = ${hookName}()${dateCast ? DATE_CAST : ""};`,
      "  return (",
      ...leafJsx(field.spec, "field", "{label}", "    "),
      "  );",
      "};",
      "",
    ].join("\n"),
  };
};

const objectSectionFile = (
  naming: Naming,
  section: SectionPlan,
  plan: Plan,
): ModuleFile => {
  const spec = section.spec as ObjectSpec;
  const propsType = `${section.componentName}Props`;
  const hookName = `use${section.componentName}`;
  const own = (segments: readonly string[]): FieldPlan | undefined =>
    plan.fields.find((f) => f.segments.join(".") === segments.join("."));

  const body = (
    fields: readonly NamedField[],
    segments: readonly string[],
    indent: string,
  ): readonly string[] =>
    fields.flatMap((field): readonly string[] => {
      if (isUnaddressable(field.name)) {
        return [
          `${indent}{/* TODO: field ${commentText(q(field.name))} skipped — "." in a key is not path-addressable (see formstand docs) */}`,
        ];
      }
      const at = [...segments, field.name];
      switch (field.spec.kind) {
        case "object":
          return [
            `${indent}<fieldset>`,
            `${indent}  <legend>${jsxText(field.label)}</legend>`,
            ...body(field.spec.fields, at, `${indent}  `),
            `${indent}</fieldset>`,
          ];
        case "array":
          return [
            `${indent}{/* TODO: nested array ${commentText(q(at.join(".")))} — extract a row component with its own ${naming.hook("FieldArray")} */}`,
          ];
        default: {
          const planned = own(at);
          return planned === undefined
            ? []
            : [`${indent}<${planned.componentName} />`];
        }
      }
    });

  const imports = collectLeaves(spec.fields, [section.key])
    .map(({ segments }) => own(segments))
    .flatMap((planned) => (planned === undefined ? [] : [planned]))
    .map(
      (planned) =>
        `import { ${planned.componentName} } from "../fields/${planned.componentName}";`,
    );

  return {
    path: `sections/${section.componentName}.tsx`,
    content: [
      HEADER,
      `import { ${naming.hook("IsDirty")}, ${naming.hook("IsValid")} } from "../hooks";`,
      ...imports,
      "",
      `export type ${propsType} = Readonly<{ heading?: string }>;`,
      "",
      "// The section hook is the path-scoped flags: dirty/valid for this",
      "// subtree only, as boolean-only subscriptions.",
      `export const ${hookName} = () => ({`,
      `  dirty: ${naming.hook("IsDirty")}(${q(section.key)}),`,
      `  valid: ${naming.hook("IsValid")}(${q(section.key)}),`,
      "});",
      "",
      `export const ${section.componentName} = ({`,
      `  heading = ${q(section.label)},`,
      `}: ${propsType}) => {`,
      `  const { dirty, valid } = ${hookName}();`,
      "  return (",
      "    <fieldset>",
      "      <legend>",
      "        {heading}",
      `        {dirty ? " — edited" : ""}`,
      `        {valid ? "" : " — has errors"}`,
      "      </legend>",
      ...body(spec.fields, [section.key], "      "),
      "    </fieldset>",
      "  );",
      "};",
      "",
    ].join("\n"),
  };
};

const arraySectionFile = (
  naming: Naming,
  section: SectionPlan,
): ModuleFile => {
  const spec = section.spec as Extract<FieldSpec, Readonly<{ kind: "array" }>>;
  const propsType = `${section.componentName}Props`;
  const hookName = `use${section.componentName}`;
  const rowName = `${section.componentName.replace(/Section$/, "")}Row`;
  const emptyName = `empty${section.componentName.replace(/Section$/, "")}Item`;
  const itemLeaves =
    spec.item.kind === "object"
      ? spec.item.fields.filter(
          (field) => !isUnaddressable(field.name) && isScalar(field.spec),
        )
      : [];
  const itemTodos =
    spec.item.kind === "object"
      ? spec.item.fields.flatMap((field) => {
          if (isUnaddressable(field.name)) {
            return [
              `      {/* TODO: field ${commentText(q(field.name))} skipped — "." in a key is not path-addressable (see formstand docs) */}`,
            ];
          }
          return isScalar(field.spec)
            ? []
            : [
                `      {/* TODO: nested ${field.spec.kind} ${commentText(q(`${section.key}.$\{index}.${field.name}`))} — extract a row component with its own hook */}`,
              ];
        })
      : [];

  const used = new Set<string>(["index", "onRemove", "field"]);
  const rowVars = itemLeaves.map((field) => {
    const base = camelCase(field.name).length === 0 ? "value" : camelCase(field.name);
    const name = `${base}${identifierSuffix(base, used)}`;
    used.add(name);
    return { field, varName: name };
  });

  const builders = buildersUsed(
    spec.item.kind === "object"
      ? itemLeaves.map((f) => f.spec)
      : [spec.item],
  );

  const rowBindings =
    spec.item.kind === "object"
      ? rowVars.map(
          ({ field, varName }) =>
            `  const ${varName} = ${naming.hook("Field")}(\`${templateEscape(section.key)}.\${index}.${templateEscape(field.name)}\`)${isDateBinding(field.spec) ? DATE_CAST : ""};`,
        )
      : [
          `  const field = ${naming.hook("Field")}(\`${templateEscape(section.key)}.\${index}\`)${isDateBinding(spec.item) ? DATE_CAST : ""};`,
        ];

  const anyDateBinding =
    spec.item.kind === "object"
      ? itemLeaves.some((field) => isDateBinding(field.spec))
      : isDateBinding(spec.item);

  const rowBody =
    spec.item.kind === "object"
      ? [
          ...rowVars.flatMap(({ field, varName }) =>
            leafControl(field.spec, varName, jsxText(field.label), "      "),
          ),
          ...itemTodos,
        ]
      : leafControl(spec.item, "field", jsxText(section.label), "      ");

  return {
    path: `sections/${section.componentName}.tsx`,
    content: [
      HEADER,
      `import { ${[...(anyDateBinding ? ["type UseFieldReturn"] : []), ...builders].join(", ")} } from "formstand";`,
      "import {",
      `  ${naming.hook("Field")},`,
      `  ${naming.hook("FieldArray")},`,
      `  ${naming.hook("IsDirty")},`,
      `  ${naming.hook("IsValid")},`,
      `} from "../hooks";`,
      `import type { ${naming.valuesType} } from "../types";`,
      "",
      `export type ${propsType} = Readonly<{ heading?: string }>;`,
      "",
      "// The array section's hook carries the field array alongside the",
      "// path-scoped flags; row fields bind template paths, so they stay",
      "// schema-typed.",
      `export const ${hookName} = () => ({`,
      `  rows: ${naming.hook("FieldArray")}(${q(section.key)}),`,
      `  dirty: ${naming.hook("IsDirty")}(${q(section.key)}),`,
      `  valid: ${naming.hook("IsValid")}(${q(section.key)}),`,
      "});",
      "",
      `const ${emptyName} = ${emitInitialValues(spec.item, 0)} as unknown as NonNullable<${naming.valuesType}[${q(section.key)}]>[number];`,
      "",
      `const ${rowName} = ({`,
      "  index,",
      "  onRemove,",
      "}: Readonly<{ index: number; onRemove: () => void }>) => {",
      ...rowBindings,
      "  return (",
      "    <fieldset>",
      `      <legend>${jsxText(`${section.label} #`)}{index + 1}</legend>`,
      ...rowBody,
      `      <button type="button" onClick={onRemove}>`,
      "        Remove",
      "      </button>",
      "    </fieldset>",
      "  );",
      "};",
      "",
      `export const ${section.componentName} = ({`,
      `  heading = ${q(section.label)},`,
      `}: ${propsType}) => {`,
      `  const { rows, dirty, valid } = ${hookName}();`,
      "  return (",
      "    <fieldset>",
      "      <legend>",
      "        {heading}",
      `        {dirty ? " — edited" : ""}`,
      `        {valid ? "" : " — has errors"}`,
      "      </legend>",
      "      {rows.fields.map((row, index) => (",
      `        <${rowName}`,
      "          key={row.id}",
      "          index={index}",
      "          onRemove={() => rows.remove(index)}",
      "        />",
      "      ))}",
      "      {rows.error ? <p role=\"alert\">{rows.error[0]}</p> : null}",
      `      <button type="button" onClick={() => rows.push(${emptyName})}>`,
      `        ${jsxText(`Add ${section.label.toLowerCase()}`)}`,
      "      </button>",
      "    </fieldset>",
      "  );",
      "};",
      "",
    ].join("\n"),
  };
};

const formFile = (naming: Naming, plan: Plan): ModuleFile => ({
  path: `${naming.formName}.tsx`,
  content: [
    HEADER,
    `import { ${naming.formConst}, ${naming.hook("IsSubmitting")} } from "./hooks";`,
    ...plan.rootFields.map(
      (field) =>
        `import { ${field.componentName} } from "./fields/${field.componentName}";`,
    ),
    ...plan.sections.map(
      (section) =>
        `import { ${section.componentName} } from "./sections/${section.componentName}";`,
    ),
    "",
    "// The form body composes sections; sections compose fields; fields bind",
    "// paths. Nothing in this tree passes `form` — every hook comes pre-wired",
    "// from ./hooks.",
    `export const ${naming.formName} = () => {`,
    `  const submitting = ${naming.hook("IsSubmitting")}();`,
    "  return (",
    "    <form",
    `      onSubmit={${naming.formConst}.handleSubmit((data) => {`,
    `        console.log("submit", data);`,
    "      })}",
    "    >",
    ...plan.rootTodos.map((todo) => `      ${todo}`),
    ...plan.rootFields.map((field) => `      <${field.componentName} />`),
    ...plan.sections.map((section) => `      <${section.componentName} />`),
    `      <button type="submit" disabled={submitting}>`,
    `        {submitting ? "Submitting..." : "Submit"}`,
    "      </button>",
    "    </form>",
    "  );",
    "};",
    "",
  ].join("\n"),
});

const indexFile = (naming: Naming): ModuleFile => ({
  path: "index.ts",
  content: [
    HEADER,
    `export { ${naming.formName} } from "./${naming.formName}";`,
    "// The form and its pre-wired hooks are the module's public API.",
    `export * from "./hooks";`,
    "",
  ].join("\n"),
});

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export const emitModuleForm = (
  options: EmitModuleOptions,
): readonly ModuleFile[] => {
  const root = assertObjectRoot(options.ir);
  const naming = namingFor(options.formName);
  const plan = buildPlan(root);

  return [
    schemaFile(options.schemaImport, options.schemaSource),
    typesFile(naming, options.schemaImport),
    hooksFile(naming, options.schemaImport, root, plan),
    ...plan.fields.map((field) => fieldFile(naming, field)),
    ...plan.sections.map((section) =>
      section.spec.kind === "object"
        ? objectSectionFile(naming, section, plan)
        : arraySectionFile(naming, section),
    ),
    formFile(naming, plan),
    indexFile(naming),
  ];
};

// Re-exported for the CLI's stdout mode and tests.
export const joinModuleFiles = (files: readonly ModuleFile[]): string =>
  files
    .map((file) => `// --- file: ${file.path}\n${file.content}`)
    .join("\n");
