import { camelCase, pascalCase } from "./casing";
import {
  DEFAULT_VISUAL,
  type EmitFormOptions,
  type KindUsage,
  type ObjectSpec,
  type SchemaImport,
  type VisualOptions,
  assertObjectRoot,
  collectUsage,
  commentText,
  emitInitialValues,
  identifierSuffix,
  isUnaddressable,
  jsxText,
  muiAdapterSection,
  q,
  shadcnAdapterSection,
  templateEscape,
} from "./codegen";
import { type FieldSpec, type NamedField, labelFromName } from "./ir";

// The --layout module emitter: instead of one file, a feature-module folder
// in the shape of the Onboarding playground demo —
//
//   schema.ts        the zod schema (re-exported in zod mode, generated in
//                    type mode) as the module's single import path for it
//   types.ts         the draft value types
//   hooks.ts         createForm + createFormHooks(form, name): the module's
//                    pre-wired hook API
//   adapter.ts(x)    (mui/shadcn only) the kit adapter the single-file
//                    backends inline, exported once for the whole module
//   fields/*.tsx     one file per scalar leaf outside arrays — props type,
//                    field hook, component
//   sections/*.tsx   one file per top-level object or array — props type,
//                    section hook (path-scoped dirty/valid flags), component
//   {Name}Form.tsx   the body composing sections and root-level fields
//   index.ts         the folder's public API
//
// Requires formstand >= 0.7 (createFormHooks). Everything is a pure string
// builder over the IR, like the single-file backends.

export type ModuleUi = "plain" | "mui" | "shadcn";

export type ModuleFile = Readonly<{
  // Forward-slash relative path inside the module folder.
  path: string;
  content: string;
}>;

export type EmitModuleOptions = EmitFormOptions &
  Readonly<{
    ui?: ModuleUi;
    // Type mode passes the generated schema source; zod mode omits it and
    // schema.ts re-exports the user's module via schemaImport.from.
    schemaSource?: string;
  }>;

const HEADER = "// Generated by formstand-cli — edit freely, this file is yours.";

// ---------------------------------------------------------------------------
// Naming
// ---------------------------------------------------------------------------

type Naming = Readonly<{
  formName: string; // ProfileForm
  prefix: string; // Profile
  factoryArg: string; // profile
  formConst: string; // profileForm
  valuesType: string; // ProfileValues
  schemaType: string; // ProfileSchema
  hook: (suffix: string) => string; // hook("Field") -> useProfileField
}>;

const namingFor = (formName: string): Naming => {
  const stripped = formName.replace(/Form$/, "");
  const prefix = pascalCase(stripped.length === 0 ? formName : stripped);
  return {
    formName,
    prefix,
    factoryArg: camelCase(prefix),
    formConst: `${camelCase(prefix)}Form`,
    valuesType: `${prefix}Values`,
    schemaType: `${prefix}Schema`,
    hook: (suffix) => `use${prefix}${suffix}`,
  };
};

// ---------------------------------------------------------------------------
// Collection: walk the root once, planning files and section bodies
// ---------------------------------------------------------------------------

type FieldPlan = Readonly<{
  segments: readonly string[];
  componentName: string; // CityField (identifierSuffix-deduped)
  spec: FieldSpec;
  label: string;
}>;

type SectionPlan = Readonly<{
  key: string;
  componentName: string; // AddressSection (deduped)
  label: string;
  spec: ObjectSpec | Extract<FieldSpec, Readonly<{ kind: "array" }>>;
}>;

type Plan = Readonly<{
  fields: readonly FieldPlan[];
  sections: readonly SectionPlan[];
  rootFields: readonly FieldPlan[]; // top-level scalars, rendered in the body
  rootTodos: readonly string[]; // dot-keys etc. surfaced in the body
}>;

const isScalar = (spec: FieldSpec): boolean =>
  spec.kind !== "object" && spec.kind !== "array";

// Scalar leaves under `fields` that are NOT inside an array (array rows bind
// dynamic paths inline in their section file instead).
const collectLeaves = (
  fields: readonly NamedField[],
  segments: readonly string[],
): readonly Readonly<{ segments: readonly string[]; field: NamedField }>[] =>
  fields.flatMap((field) => {
    if (isUnaddressable(field.name)) return [];
    const at = [...segments, field.name];
    switch (field.spec.kind) {
      case "object":
        return collectLeaves(field.spec.fields, at);
      case "array":
        return [];
      default:
        return [{ segments: at, field }];
    }
  });

const buildPlan = (root: ObjectSpec): Plan => {
  const used = new Set<string>();
  const claim = (base: string): string => {
    const name = `${base}${identifierSuffix(base, used)}`;
    used.add(name);
    return name;
  };

  const planField = (
    segments: readonly string[],
    field: NamedField,
  ): FieldPlan => ({
    segments,
    componentName: claim(`${pascalCase(segments[segments.length - 1] ?? "")}Field`),
    spec: field.spec,
    label: field.label,
  });

  const rootFields = root.fields
    .filter((field) => !isUnaddressable(field.name) && isScalar(field.spec))
    .map((field) => planField([field.name], field));

  const sections = root.fields
    .filter(
      (field) =>
        !isUnaddressable(field.name) &&
        (field.spec.kind === "object" || field.spec.kind === "array"),
    )
    .map(
      (field): SectionPlan => ({
        key: field.name,
        componentName: claim(`${pascalCase(field.name)}Section`),
        label: field.label,
        spec: field.spec as SectionPlan["spec"],
      }),
    );

  const sectionLeafFields = sections.flatMap((section) =>
    section.spec.kind === "object"
      ? collectLeaves(section.spec.fields, [section.key]).map(
          ({ segments, field }) => planField(segments, field),
        )
      : [],
  );

  const rootTodos = root.fields
    .filter((field) => isUnaddressable(field.name))
    .map(
      (field) =>
        `{/* TODO: field ${commentText(q(field.name))} skipped — "." in a key is not path-addressable (see formstand docs) */}`,
    );

  return {
    fields: [...rootFields, ...sectionLeafFields],
    sections,
    rootFields,
    rootTodos,
  };
};

// ---------------------------------------------------------------------------
// Leaf rendering, per kit
// ---------------------------------------------------------------------------

const todoTexts = (spec: FieldSpec): readonly string[] => [
  ...(spec.todo !== undefined ? [commentText(spec.todo)] : []),
  ...(spec.kind === "date"
    ? [
        "date input — swap in a date picker; this binds a Date-typed field as plain text through a cast",
      ]
    : []),
];

// Date-typed fields bind a text input, so the hook result is cast to the
// string shape the prop builders take — flagged by the TODO the file gets.
const isDateBinding = (spec: FieldSpec): boolean => spec.kind === "date";

const DATE_CAST = " as unknown as UseFieldReturn<string | null | undefined>";

type ImportLine = Readonly<{ from: string; names: readonly string[] }>;

// Merge import needs per module specifier, preserving first-seen order.
const mergeImports = (lines: readonly ImportLine[]): readonly string[] => {
  const byFrom = lines.reduce<ReadonlyMap<string, readonly string[]>>(
    (acc, line) => {
      const existing = acc.get(line.from) ?? [];
      const merged = [
        ...existing,
        ...line.names.filter((name) => !existing.includes(name)),
      ];
      return new Map([...acc, [line.from, merged]]);
    },
    new Map(),
  );
  return [...byFrom.entries()]
    .filter(([, names]) => names.length > 0)
    .map(([from, names]) => `import { ${names.join(", ")} } from ${q(from)};`);
};

// What one leaf control needs imported, per kit. Builder names double as
// the adapter's exports for the kit uis.
const leafImports = (ui: ModuleUi, spec: FieldSpec): readonly ImportLine[] => {
  switch (ui) {
    case "plain": {
      const builder =
        spec.kind === "number"
          ? "numberInputProps"
          : spec.kind === "boolean"
            ? "checkboxProps"
            : spec.kind === "enum"
              ? "selectProps"
              : "textInputProps";
      return [{ from: "formstand", names: [builder] }];
    }
    case "mui":
      switch (spec.kind) {
        case "boolean":
          return [
            { from: "@mui/material", names: ["FormControlLabel", "Switch"] },
            { from: "../adapter", names: ["muiSwitchProps"] },
          ];
        case "enum":
          return [
            { from: "@mui/material", names: ["MenuItem", "TextField"] },
            { from: "../adapter", names: ["muiSelectProps"] },
          ];
        case "number":
          return [
            { from: "@mui/material", names: ["TextField"] },
            { from: "../adapter", names: ["muiNumberFieldProps"] },
          ];
        default:
          return [
            { from: "@mui/material", names: ["TextField"] },
            { from: "../adapter", names: ["muiTextFieldProps"] },
          ];
      }
    case "shadcn":
      switch (spec.kind) {
        case "boolean":
          return [
            { from: "@/components/ui/checkbox", names: ["Checkbox"] },
            { from: "@/components/ui/label", names: ["Label"] },
            { from: "../adapter", names: ["FieldError", "shadcnCheckboxProps"] },
          ];
        case "enum":
          return [
            { from: "@/components/ui/label", names: ["Label"] },
            {
              from: "@/components/ui/select",
              names: [
                "Select",
                "SelectContent",
                "SelectItem",
                "SelectTrigger",
                "SelectValue",
              ],
            },
            {
              from: "../adapter",
              names: ["FieldError", "ariaInvalid", "shadcnSelectProps"],
            },
          ];
        case "number":
          return [
            { from: "@/components/ui/input", names: ["Input"] },
            { from: "@/components/ui/label", names: ["Label"] },
            {
              from: "../adapter",
              names: ["FieldError", "shadcnNumberInputProps"],
            },
          ];
        default:
          return [
            { from: "@/components/ui/input", names: ["Input"] },
            { from: "@/components/ui/label", names: ["Label"] },
            { from: "../adapter", names: ["FieldError", "shadcnTextInputProps"] },
          ];
      }
  }
};

// The labeled control for one leaf bound to `varName`, at `indent`.
// `labelAttr` is a JSX expression container string (e.g. `{label}` or
// `{"Email"}`); `idAttr` likewise, or undefined where the kit needs none.
const leafJsx = (
  ui: ModuleUi,
  spec: FieldSpec,
  varName: string,
  labelAttr: string,
  idAttr: string | undefined,
  indent: string,
): readonly string[] => {
  switch (ui) {
    case "plain": {
      const control =
        spec.kind === "enum"
          ? [
              `${indent}    <select {...selectProps(${varName})}>`,
              `${indent}      <option value="">{"Select…"}</option>`,
              ...spec.options.map(
                (option) =>
                  `${indent}      <option value=${jsxText(option)}>${jsxText(labelFromName(option))}</option>`,
              ),
              `${indent}    </select>`,
            ]
          : [
              `${indent}    <input${spec.kind === "date" ? ' type="date"' : ""} {...${
                spec.kind === "number"
                  ? "numberInputProps"
                  : spec.kind === "boolean"
                    ? "checkboxProps"
                    : "textInputProps"
              }(${varName})} />`,
            ];
      return [
        `${indent}<div>`,
        `${indent}  <label>`,
        `${indent}    ${labelAttr}`,
        ...control,
        `${indent}  </label>`,
        `${indent}  {${varName}.error?.[0] !== undefined ? (`,
        `${indent}    <p role="alert">{${varName}.error?.[0]}</p>`,
        `${indent}  ) : null}`,
        `${indent}</div>`,
      ];
    }
    case "mui":
      switch (spec.kind) {
        case "boolean":
          return [
            `${indent}<FormControlLabel`,
            `${indent}  label=${labelAttr}`,
            `${indent}  control={<Switch {...muiSwitchProps(${varName})} />}`,
            `${indent}/>`,
          ];
        case "enum":
          return [
            `${indent}<TextField select fullWidth label=${labelAttr} {...muiSelectProps(${varName})}>`,
            ...spec.options.map(
              (option) =>
                `${indent}  <MenuItem value=${jsxText(option)}>${jsxText(labelFromName(option))}</MenuItem>`,
            ),
            `${indent}</TextField>`,
          ];
        case "number":
          return [
            `${indent}<TextField fullWidth label=${labelAttr} {...muiNumberFieldProps(${varName})} />`,
          ];
        default:
          return [
            `${indent}<TextField fullWidth label=${labelAttr} {...muiTextFieldProps(${varName})} />`,
          ];
      }
    case "shadcn": {
      const id = idAttr ?? `{${q("")}}`;
      switch (spec.kind) {
        case "boolean":
          return [
            `${indent}<div className="grid gap-2">`,
            `${indent}  <div className="flex items-center gap-2">`,
            `${indent}    <Checkbox id=${id} {...shadcnCheckboxProps(${varName})} />`,
            `${indent}    <Label htmlFor=${id}>${labelAttr}</Label>`,
            `${indent}  </div>`,
            `${indent}  <FieldError field={${varName}} />`,
            `${indent}</div>`,
          ];
        case "enum":
          return [
            `${indent}<div className="grid gap-2">`,
            `${indent}  <Label htmlFor=${id}>${labelAttr}</Label>`,
            `${indent}  <Select {...shadcnSelectProps(${varName})}>`,
            `${indent}    <SelectTrigger`,
            `${indent}      id=${id}`,
            `${indent}      className="w-full"`,
            `${indent}      aria-invalid={ariaInvalid(${varName})}`,
            `${indent}    >`,
            `${indent}      <SelectValue placeholder=${labelAttr} />`,
            `${indent}    </SelectTrigger>`,
            `${indent}    <SelectContent>`,
            ...spec.options.map(
              (option) =>
                `${indent}      <SelectItem value=${jsxText(option)}>${jsxText(labelFromName(option))}</SelectItem>`,
            ),
            `${indent}    </SelectContent>`,
            `${indent}  </Select>`,
            `${indent}  <FieldError field={${varName}} />`,
            `${indent}</div>`,
          ];
        default: {
          const builder =
            spec.kind === "number"
              ? "shadcnNumberInputProps"
              : "shadcnTextInputProps";
          return [
            `${indent}<div className="grid gap-2">`,
            `${indent}  <Label htmlFor=${id}>${labelAttr}</Label>`,
            `${indent}  <Input id=${id}${spec.kind === "date" ? ' type="date"' : ""} {...${builder}(${varName})} />`,
            `${indent}  <FieldError field={${varName}} />`,
            `${indent}</div>`,
          ];
        }
      }
    }
  }
};

// Same, prefixed with JSX-comment TODOs — safe only in child position
// (a comment container can't precede the return expression itself).
const leafControl = (
  ui: ModuleUi,
  spec: FieldSpec,
  varName: string,
  labelAttr: string,
  idAttr: string | undefined,
  indent: string,
): readonly string[] => [
  ...todoTexts(spec).map((text) => `${indent}{/* TODO: ${text} */}`),
  ...leafJsx(ui, spec, varName, labelAttr, idAttr, indent),
];

// ---------------------------------------------------------------------------
// Kit shells (sections, array rows, form body)
// ---------------------------------------------------------------------------

const headingLines = (indent: string): readonly string[] => [
  `${indent}{heading}`,
  `${indent}{dirty ? " — edited" : ""}`,
  `${indent}{valid ? "" : " — has errors"}`,
];

// Section wrappers are where --sections and --columns land: the wrapper
// picks the chrome (flat / panel / collapsible) and its content container is
// the grid the fields flow into. The 1-column flat default keeps the
// historical output verbatim.
const objectShell = (
  ui: ModuleUi,
  visual: VisualOptions,
  children: readonly string[],
): readonly string[] => {
  const cols = visual.columns;
  switch (ui) {
    case "mui": {
      const gridSx = `display: "grid", gridTemplateColumns: "repeat(${cols}, minmax(0, 1fr))", gap: 2`;
      switch (visual.sections) {
        case "flat":
          return cols === 1
            ? [
                "    <Stack spacing={2}>",
                `      <Typography variant="subtitle1">`,
                ...headingLines("        "),
                "      </Typography>",
                ...children,
                "    </Stack>",
              ]
            : [
                `    <Box sx={{ ${gridSx} }}>`,
                `      <Typography variant="subtitle1" sx={{ gridColumn: "1 / -1" }}>`,
                ...headingLines("        "),
                "      </Typography>",
                ...children,
                "    </Box>",
              ];
        case "panel":
          return [
            `    <Card variant="outlined">`,
            `      <CardContent sx={{ ${gridSx} }}>`,
            `        <Typography variant="subtitle1"${cols > 1 ? ` sx={{ gridColumn: "1 / -1" }}` : ""}>`,
            ...headingLines("          "),
            "        </Typography>",
            ...children,
            "      </CardContent>",
            "    </Card>",
          ];
        case "collapsible":
          return [
            `    <Accordion defaultExpanded variant="outlined" disableGutters>`,
            `      <AccordionSummary expandIcon={<span aria-hidden>{"▾"}</span>}>`,
            `        <Typography variant="subtitle1">`,
            ...headingLines("          "),
            "        </Typography>",
            "      </AccordionSummary>",
            `      <AccordionDetails sx={{ ${gridSx} }}>`,
            ...children,
            "      </AccordionDetails>",
            "    </Accordion>",
          ];
      }
      break;
    }
    case "shadcn": {
      const colsClass = cols > 1 ? ` md:grid-cols-${cols}` : "";
      switch (visual.sections) {
        case "flat":
        case "panel":
          return [
            `    <fieldset className="grid gap-4 rounded-lg border p-4${visual.sections === "panel" ? " bg-card text-card-foreground shadow-sm" : ""}${colsClass}">`,
            `      <legend className="px-1 text-sm font-medium">`,
            ...headingLines("        "),
            "      </legend>",
            ...children,
            "    </fieldset>",
          ];
        case "collapsible":
          return [
            `    <details open className="rounded-lg border">`,
            `      <summary className="cursor-pointer select-none px-4 py-3 text-sm font-medium">`,
            ...headingLines("        "),
            "      </summary>",
            `      <div className="grid gap-4 px-4 pb-4${colsClass}">`,
            ...children,
            "      </div>",
            "    </details>",
          ];
      }
      break;
    }
    case "plain": {
      const grid =
        cols > 1
          ? `display: "grid", gridTemplateColumns: "repeat(${cols}, minmax(0, 1fr))", gap: 16`
          : "";
      switch (visual.sections) {
        case "flat":
        case "panel": {
          const style = [
            ...(grid === "" ? [] : [grid]),
            ...(visual.sections === "panel"
              ? [`border: "1px solid #d0d7e2", borderRadius: 8, padding: 16, margin: 0`]
              : []),
          ].join(", ");
          return [
            `    <fieldset${style === "" ? "" : ` style={{ ${style} }}`}>`,
            `      <legend${visual.sections === "panel" ? ` style={{ padding: "0 6px", fontWeight: 600 }}` : ""}>`,
            ...headingLines("        "),
            "      </legend>",
            ...children,
            "    </fieldset>",
          ];
        }
        case "collapsible":
          return [
            "    <details open>",
            `      <summary style={{ cursor: "pointer", fontWeight: 600 }}>`,
            ...headingLines("        "),
            "      </summary>",
            ...(grid === ""
              ? children
              : [`      <div style={{ ${grid} }}>`, ...children, "      </div>"]),
            "    </details>",
          ];
      }
      break;
    }
  }
  return children;
};

const objectSectionImports = (
  ui: ModuleUi,
  visual: VisualOptions,
): readonly ImportLine[] => {
  if (ui !== "mui") return [];
  switch (visual.sections) {
    case "flat":
      return [
        {
          from: "@mui/material",
          names:
            visual.columns === 1 ? ["Stack", "Typography"] : ["Box", "Typography"],
        },
      ];
    case "panel":
      return [
        { from: "@mui/material", names: ["Card", "CardContent", "Typography"] },
      ];
    case "collapsible":
      return [
        {
          from: "@mui/material",
          names: [
            "Accordion",
            "AccordionDetails",
            "AccordionSummary",
            "Typography",
          ],
        },
      ];
  }
};

type ArrayShellParts = Readonly<{
  imports: readonly ImportLine[];
  rowOpen: readonly string[]; // wraps the row body inside the Row component
  rowClose: (removeExpr: string) => readonly string[];
  listError: readonly string[]; // rows.error rendering
  addButton: (pushExpr: string, addLabel: string) => readonly string[];
}>;

const arrayShell = (ui: ModuleUi, sectionLabel: string): ArrayShellParts => {
  switch (ui) {
    case "mui":
      return {
        imports: [
          { from: "@mui/material", names: ["Button", "Stack", "Typography"] },
        ],
        rowOpen: [
          "    <Stack",
          "      spacing={2}",
          `      sx={{ p: 2, border: 1, borderColor: "divider", borderRadius: 1 }}`,
          "    >",
        ],
        rowClose: (removeExpr) => [
          `      <Button type="button" onClick={${removeExpr}}>`,
          "        Remove",
          "      </Button>",
          "    </Stack>",
        ],
        listError: [
          "      {rows.error ? (",
          `        <Typography color="error">{rows.error[0]}</Typography>`,
          "      ) : null}",
        ],
        addButton: (pushExpr, addLabel) => [
          `      <Button type="button" onClick={${pushExpr}}>`,
          `        ${jsxText(addLabel)}`,
          "      </Button>",
        ],
      };
    case "shadcn":
      return {
        imports: [{ from: "@/components/ui/button", names: ["Button"] }],
        rowOpen: [`    <div className="grid gap-4 rounded-lg border p-4">`],
        rowClose: (removeExpr) => [
          "      <Button",
          `        type="button"`,
          `        variant="outline"`,
          `        size="sm"`,
          `        className="w-fit"`,
          `        onClick={${removeExpr}}`,
          "      >",
          "        Remove",
          "      </Button>",
          "    </div>",
        ],
        listError: [
          `      {rows.error ? <p role="alert">{rows.error[0]}</p> : null}`,
        ],
        addButton: (pushExpr, addLabel) => [
          "      <Button",
          `        type="button"`,
          `        variant="outline"`,
          `        size="sm"`,
          `        className="w-fit"`,
          `        onClick={${pushExpr}}`,
          "      >",
          `        ${jsxText(addLabel)}`,
          "      </Button>",
        ],
      };
    case "plain":
      return {
        imports: [],
        rowOpen: [
          "    <fieldset>",
          `      <legend>${jsxText(`${sectionLabel} #`)}{index + 1}</legend>`,
        ],
        rowClose: (removeExpr) => [
          `      <button type="button" onClick={${removeExpr}}>`,
          "        Remove",
          "      </button>",
          "    </fieldset>",
        ],
        listError: [
          `      {rows.error ? <p role="alert">{rows.error[0]}</p> : null}`,
        ],
        addButton: (pushExpr, addLabel) => [
          `      <button type="button" onClick={${pushExpr}}>`,
          `        ${jsxText(addLabel)}`,
          "      </button>",
        ],
      };
  }
};

type FormShell = Readonly<{
  imports: readonly ImportLine[];
  open: (naming: Naming) => readonly string[];
  close: readonly string[];
  bodyIndent: string;
}>;

const formShell = (ui: ModuleUi): FormShell => {
  switch (ui) {
    case "mui":
      return {
        imports: [{ from: "@mui/material", names: ["Box", "Button", "Stack"] }],
        open: (naming) => [
          "    <Box",
          `      component="form"`,
          `      onSubmit={${naming.formConst}.handleSubmit((data) => {`,
          `        console.log("submit", data);`,
          "      })}",
          "      sx={{ maxWidth: 640 }}",
          "    >",
          "      <Stack spacing={2}>",
        ],
        close: [
          `        <Button type="submit" variant="contained" disabled={submitting}>`,
          `          {submitting ? "Submitting..." : "Submit"}`,
          "        </Button>",
          "      </Stack>",
          "    </Box>",
        ],
        bodyIndent: "        ",
      };
    case "shadcn":
      return {
        imports: [{ from: "@/components/ui/button", names: ["Button"] }],
        open: (naming) => [
          "    <form",
          `      className="grid max-w-xl gap-4"`,
          `      onSubmit={${naming.formConst}.handleSubmit((data) => {`,
          `        console.log("submit", data);`,
          "      })}",
          "    >",
        ],
        close: [
          `      <Button type="submit" disabled={submitting}>`,
          `        {submitting ? "Submitting..." : "Submit"}`,
          "      </Button>",
          "    </form>",
        ],
        bodyIndent: "      ",
      };
    case "plain":
      return {
        imports: [],
        open: (naming) => [
          "    <form",
          `      onSubmit={${naming.formConst}.handleSubmit((data) => {`,
          `        console.log("submit", data);`,
          "      })}",
          "    >",
        ],
        close: [
          `      <button type="submit" disabled={submitting}>`,
          `        {submitting ? "Submitting..." : "Submit"}`,
          "      </button>",
          "    </form>",
        ],
        bodyIndent: "      ",
      };
  }
};

// ---------------------------------------------------------------------------
// File emitters
// ---------------------------------------------------------------------------

const schemaFile = (
  schemaImport: SchemaImport,
  schemaSource: string | undefined,
): ModuleFile => ({
  path: "schema.ts",
  content:
    schemaSource !== undefined
      ? `${HEADER}\n${schemaSource}`
      : [
          HEADER,
          "// The schema's source of truth stays where it was; this re-export",
          "// gives every file in the module one import path for it.",
          schemaImport.kind === "default"
            ? `export { default as ${schemaImport.name} } from ${q(schemaImport.from)};`
            : `export { ${schemaImport.name} } from ${q(schemaImport.from)};`,
          "",
        ].join("\n"),
});

const typesFile = (naming: Naming, schemaImport: SchemaImport): ModuleFile => ({
  path: "types.ts",
  content: [
    HEADER,
    `import type { z } from "zod";`,
    `import { ${schemaImport.name} } from "./schema";`,
    "",
    `export type ${naming.schemaType} = typeof ${schemaImport.name};`,
    "",
    "// The draft shape the hooks read and write (z.input: what the form",
    "// holds while being filled, before validation refines it).",
    `export type ${naming.valuesType} = z.input<${naming.schemaType}>;`,
    "",
  ].join("\n"),
});

const hooksFile = (
  naming: Naming,
  schemaImport: SchemaImport,
  root: ObjectSpec,
  plan: Plan,
): ModuleFile => {
  const hasArrays = plan.sections.some((s) => s.spec.kind === "array");
  const hasFields = plan.fields.length > 0 || hasArrays;
  const hooks = [
    ...(hasFields ? [naming.hook("Field")] : []),
    ...(hasArrays ? [naming.hook("FieldArray")] : []),
    ...(plan.sections.length > 0
      ? [naming.hook("IsDirty"), naming.hook("IsValid")]
      : []),
    naming.hook("IsSubmitting"),
  ];
  return {
    path: "hooks.ts",
    content: [
      HEADER,
      `import { createForm, createFormHooks } from "formstand";`,
      `import { ${schemaImport.name} } from "./schema";`,
      `import type { ${naming.valuesType} } from "./types";`,
      "",
      "// A form starts blank: required numbers/dates/enums begin undefined, so",
      "// these initial values intentionally do not satisfy the schema yet —",
      "// hence the cast. Validation reports the gaps on submit.",
      `const initialValues = ${emitInitialValues(root, 0)} as unknown as ${naming.valuesType};`,
      "",
      "// One module-level form for the whole feature; every file below imports",
      "// these pre-wired hooks instead of receiving `form` via props or a",
      "// provider. A module singleton never unmounts — for a per-mount",
      "// lifecycle, use useForm + createFormContext instead.",
      `export const ${naming.formConst} = createForm(${schemaImport.name}, {`,
      "  initialValues,",
      `  mode: "onBlur",`,
      "});",
      "",
      "export const {",
      ...hooks.map((name) => `  ${name},`),
      `} = createFormHooks(${naming.formConst}, ${q(naming.factoryArg)});`,
      "",
    ].join("\n"),
  };
};

// The kit adapter the single-file backends inline, exported once — only for
// the kit uis, and only when some leaf actually renders a control.
const adapterFile = (ui: ModuleUi, usage: KindUsage): ModuleFile | undefined => {
  const hasLeaf =
    usage.string || usage.date || usage.number || usage.boolean || usage.enum;
  if (ui === "plain" || !hasLeaf) return undefined;
  const needsText = usage.string || usage.date;
  const needsChangeEvent = needsText || usage.number || (ui === "mui" && usage.enum);
  const formstandValues = [
    ...(usage.number ? ["numberToInputText", "parseNumberText"] : []),
  ];
  return {
    path: ui === "mui" ? "adapter.ts" : "adapter.tsx",
    content: [
      HEADER,
      ...(needsChangeEvent ? [`import type { ChangeEvent } from "react";`] : []),
      "import {",
      ...formstandValues.map((name) => `  ${name},`),
      "  type UseFieldReturn,",
      `} from "formstand";`,
      "",
      ui === "mui"
        ? muiAdapterSection(usage, "export ")
        : shadcnAdapterSection(usage, "export "),
      "",
    ].join("\n"),
  };
};

const fieldFile = (
  ui: ModuleUi,
  naming: Naming,
  field: FieldPlan,
): ModuleFile => {
  const path = field.segments.join(".");
  const propsType = `${field.componentName}Props`;
  const hookName = `use${field.componentName}`;
  const dateCast = isDateBinding(field.spec);
  const imports = mergeImports([
    ...leafImports(ui, field.spec),
    ...(dateCast ? [{ from: "formstand", names: ["type UseFieldReturn"] }] : []),
  ]);
  return {
    path: `fields/${field.componentName}.tsx`,
    content: [
      HEADER,
      ...imports,
      `import { ${naming.hook("Field")} } from "../hooks";`,
      "",
      `export type ${propsType} = Readonly<{ label?: string }>;`,
      "",
      `export const ${hookName} = () => ${naming.hook("Field")}(${q(path)});`,
      "",
      `export const ${field.componentName} = ({`,
      `  label = ${q(field.label)},`,
      `}: ${propsType}) => {`,
      ...todoTexts(field.spec).map((text) => `  // TODO: ${text}`),
      `  const field = ${hookName}()${dateCast ? DATE_CAST : ""};`,
      "  return (",
      ...leafJsx(ui, field.spec, "field", "{label}", `{${q(path)}}`, "    "),
      "  );",
      "};",
      "",
    ].join("\n"),
  };
};

const objectSectionFile = (
  ui: ModuleUi,
  visual: VisualOptions,
  naming: Naming,
  section: SectionPlan,
  plan: Plan,
): ModuleFile => {
  const spec = section.spec as ObjectSpec;
  const propsType = `${section.componentName}Props`;
  const hookName = `use${section.componentName}`;
  const own = (segments: readonly string[]): FieldPlan | undefined =>
    plan.fields.find((f) => f.segments.join(".") === segments.join("."));

  const body = (
    fields: readonly NamedField[],
    segments: readonly string[],
    indent: string,
  ): readonly string[] =>
    fields.flatMap((field): readonly string[] => {
      if (isUnaddressable(field.name)) {
        return [
          `${indent}{/* TODO: field ${commentText(q(field.name))} skipped — "." in a key is not path-addressable (see formstand docs) */}`,
        ];
      }
      const at = [...segments, field.name];
      switch (field.spec.kind) {
        case "object":
          return [
            `${indent}<fieldset${
              visual.columns > 1
                ? ui === "shadcn"
                  ? ` className="md:col-span-full"`
                  : ` style={{ gridColumn: "1 / -1" }}`
                : ""
            }>`,
            `${indent}  <legend>${jsxText(field.label)}</legend>`,
            ...body(field.spec.fields, at, `${indent}  `),
            `${indent}</fieldset>`,
          ];
        case "array":
          return [
            `${indent}{/* TODO: nested array ${commentText(q(at.join(".")))} — extract a row component with its own ${naming.hook("FieldArray")} */}`,
          ];
        default: {
          const planned = own(at);
          return planned === undefined
            ? []
            : [`${indent}<${planned.componentName} />`];
        }
      }
    });

  const fieldImports = collectLeaves(spec.fields, [section.key])
    .map(({ segments }) => own(segments))
    .flatMap((planned) => (planned === undefined ? [] : [planned]))
    .map(
      (planned) =>
        `import { ${planned.componentName} } from "../fields/${planned.componentName}";`,
    );

  return {
    path: `sections/${section.componentName}.tsx`,
    content: [
      HEADER,
      ...mergeImports(objectSectionImports(ui, visual)),
      `import { ${naming.hook("IsDirty")}, ${naming.hook("IsValid")} } from "../hooks";`,
      ...fieldImports,
      "",
      `export type ${propsType} = Readonly<{ heading?: string }>;`,
      "",
      "// The section hook is the path-scoped flags: dirty/valid for this",
      "// subtree only, as boolean-only subscriptions.",
      `export const ${hookName} = () => ({`,
      `  dirty: ${naming.hook("IsDirty")}(${q(section.key)}),`,
      `  valid: ${naming.hook("IsValid")}(${q(section.key)}),`,
      "});",
      "",
      `export const ${section.componentName} = ({`,
      `  heading = ${q(section.label)},`,
      `}: ${propsType}) => {`,
      `  const { dirty, valid } = ${hookName}();`,
      "  return (",
      ...objectShell(ui, visual, body(spec.fields, [section.key], "      ")),
      "  );",
      "};",
      "",
    ].join("\n"),
  };
};

const arraySectionFile = (
  ui: ModuleUi,
  visual: VisualOptions,
  naming: Naming,
  section: SectionPlan,
): ModuleFile => {
  const spec = section.spec as Extract<FieldSpec, Readonly<{ kind: "array" }>>;
  const propsType = `${section.componentName}Props`;
  const hookName = `use${section.componentName}`;
  const rowName = `${section.componentName.replace(/Section$/, "")}Row`;
  const emptyName = `empty${section.componentName.replace(/Section$/, "")}Item`;
  const shell = arrayShell(ui, section.label);
  const itemLeaves =
    spec.item.kind === "object"
      ? spec.item.fields.filter(
          (field) => !isUnaddressable(field.name) && isScalar(field.spec),
        )
      : [];
  const itemTodos =
    spec.item.kind === "object"
      ? spec.item.fields.flatMap((field) => {
          if (isUnaddressable(field.name)) {
            return [
              `      {/* TODO: field ${commentText(q(field.name))} skipped — "." in a key is not path-addressable (see formstand docs) */}`,
            ];
          }
          return isScalar(field.spec)
            ? []
            : [
                `      {/* TODO: nested ${field.spec.kind} ${commentText(q(`${section.key}.$\{index}.${field.name}`))} — extract a row component with its own hook */}`,
              ];
        })
      : [];

  const used = new Set<string>(["index", "onRemove", "field", "rows"]);
  const rowVars = itemLeaves.map((field) => {
    const base = camelCase(field.name).length === 0 ? "value" : camelCase(field.name);
    const name = `${base}${identifierSuffix(base, used)}`;
    used.add(name);
    return { field, varName: name };
  });

  const rowSpecs =
    spec.item.kind === "object" ? itemLeaves.map((f) => f.spec) : [spec.item];
  const anyDateBinding = rowSpecs.some(isDateBinding);

  const dynamicId = (name: string | undefined): string =>
    name === undefined
      ? `{\`${templateEscape(section.key)}.\${index}\`}`
      : `{\`${templateEscape(section.key)}.\${index}.${templateEscape(name)}\`}`;

  const rowBindings =
    spec.item.kind === "object"
      ? rowVars.map(
          ({ field, varName }) =>
            `  const ${varName} = ${naming.hook("Field")}(\`${templateEscape(section.key)}.\${index}.${templateEscape(field.name)}\`)${isDateBinding(field.spec) ? DATE_CAST : ""};`,
        )
      : [
          `  const field = ${naming.hook("Field")}(\`${templateEscape(section.key)}.\${index}\`)${isDateBinding(spec.item) ? DATE_CAST : ""};`,
        ];

  const rowBody =
    spec.item.kind === "object"
      ? [
          ...rowVars.flatMap(({ field, varName }) =>
            leafControl(
              ui,
              field.spec,
              varName,
              jsxText(field.label),
              dynamicId(field.name),
              "      ",
            ),
          ),
          ...itemTodos,
        ]
      : leafControl(
          ui,
          spec.item,
          "field",
          jsxText(section.label),
          dynamicId(undefined),
          "      ",
        );

  const imports = mergeImports([
    ...rowSpecs.flatMap((s) => leafImports(ui, s)),
    ...shell.imports,
    // The outer wrapper is objectShell, so panel/collapsible chrome pulls
    // its own components in.
    ...objectSectionImports(ui, visual),
    ...(anyDateBinding
      ? [{ from: "formstand", names: ["type UseFieldReturn"] }]
      : []),
  ]);

  return {
    path: `sections/${section.componentName}.tsx`,
    content: [
      HEADER,
      ...imports,
      "import {",
      `  ${naming.hook("Field")},`,
      `  ${naming.hook("FieldArray")},`,
      `  ${naming.hook("IsDirty")},`,
      `  ${naming.hook("IsValid")},`,
      `} from "../hooks";`,
      `import type { ${naming.valuesType} } from "../types";`,
      "",
      `export type ${propsType} = Readonly<{ heading?: string }>;`,
      "",
      "// The array section's hook carries the field array alongside the",
      "// path-scoped flags; row fields bind template paths, so they stay",
      "// schema-typed.",
      `export const ${hookName} = () => ({`,
      `  rows: ${naming.hook("FieldArray")}(${q(section.key)}),`,
      `  dirty: ${naming.hook("IsDirty")}(${q(section.key)}),`,
      `  valid: ${naming.hook("IsValid")}(${q(section.key)}),`,
      "});",
      "",
      `const ${emptyName} = ${emitInitialValues(spec.item, 0)} as unknown as NonNullable<${naming.valuesType}[${q(section.key)}]>[number];`,
      "",
      `const ${rowName} = ({`,
      "  index,",
      "  onRemove,",
      "}: Readonly<{ index: number; onRemove: () => void }>) => {",
      ...rowBindings,
      "  return (",
      ...shell.rowOpen,
      ...rowBody,
      ...shell.rowClose("onRemove"),
      "  );",
      "};",
      "",
      `export const ${section.componentName} = ({`,
      `  heading = ${q(section.label)},`,
      `}: ${propsType}) => {`,
      `  const { rows, dirty, valid } = ${hookName}();`,
      "  return (",
      ...objectShell(ui, visual, [
        "      {rows.fields.map((row, index) => (",
        `        <${rowName}`,
        "          key={row.id}",
        "          index={index}",
        "          onRemove={() => rows.remove(index)}",
        "        />",
        "      ))}",
        ...shell.listError,
        ...shell.addButton(
          `() => rows.push(${emptyName})`,
          `Add ${section.label.toLowerCase()}`,
        ),
      ]),
      "  );",
      "};",
      "",
    ].join("\n"),
  };
};

const formFile = (ui: ModuleUi, naming: Naming, plan: Plan): ModuleFile => {
  const shell = formShell(ui);
  return {
    path: `${naming.formName}.tsx`,
    content: [
      HEADER,
      ...mergeImports(shell.imports),
      `import { ${naming.formConst}, ${naming.hook("IsSubmitting")} } from "./hooks";`,
      ...plan.rootFields.map(
        (field) =>
          `import { ${field.componentName} } from "./fields/${field.componentName}";`,
      ),
      ...plan.sections.map(
        (section) =>
          `import { ${section.componentName} } from "./sections/${section.componentName}";`,
      ),
      "",
      "// The form body composes sections; sections compose fields; fields bind",
      "// paths. Nothing in this tree passes `form` — every hook comes pre-wired",
      "// from ./hooks.",
      `export const ${naming.formName} = () => {`,
      `  const submitting = ${naming.hook("IsSubmitting")}();`,
      "  return (",
      ...shell.open(naming),
      ...plan.rootTodos.map((todo) => `${shell.bodyIndent}${todo}`),
      ...plan.rootFields.map(
        (field) => `${shell.bodyIndent}<${field.componentName} />`,
      ),
      ...plan.sections.map(
        (section) => `${shell.bodyIndent}<${section.componentName} />`,
      ),
      ...shell.close,
      "  );",
      "};",
      "",
    ].join("\n"),
  };
};

const indexFile = (naming: Naming): ModuleFile => ({
  path: "index.ts",
  content: [
    HEADER,
    `export { ${naming.formName} } from "./${naming.formName}";`,
    "// The form and its pre-wired hooks are the module's public API.",
    `export * from "./hooks";`,
    "",
  ].join("\n"),
});

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export const emitModuleForm = (
  options: EmitModuleOptions,
): readonly ModuleFile[] => {
  const ui = options.ui ?? "plain";
  const visual = options.visual ?? DEFAULT_VISUAL;
  const root = assertObjectRoot(options.ir);
  const naming = namingFor(options.formName);
  const plan = buildPlan(root);
  const adapter = adapterFile(ui, collectUsage(root));

  return [
    schemaFile(options.schemaImport, options.schemaSource),
    typesFile(naming, options.schemaImport),
    hooksFile(naming, options.schemaImport, root, plan),
    ...(adapter === undefined ? [] : [adapter]),
    ...plan.fields.map((field) => fieldFile(ui, naming, field)),
    ...plan.sections.map((section) =>
      section.spec.kind === "object"
        ? objectSectionFile(ui, visual, naming, section, plan)
        : arraySectionFile(ui, visual, naming, section),
    ),
    formFile(ui, naming, plan),
    indexFile(naming),
  ];
};

// Re-exported for the CLI's stdout mode and tests.
export const joinModuleFiles = (files: readonly ModuleFile[]): string =>
  files
    .map((file) => `// --- file: ${file.path}\n${file.content}`)
    .join("\n");
