import type { SchemaImport } from "./codegen";
import { emitInitialValues, blankNeedsCast } from "./codegen";
import type { FieldSpec } from "./ir";
import type { GeneratedTestPlan } from "./testCases";

// The generated-tests emitters (design: cli/design/generated-tests.md,
// decided 2026-09-18). One component-spec production serves vitest and
// jest — the bodies are identical, only the globals import differs — and
// the Playwright spec is its own emitter, gated by the caller on a
// configured baseURL. Every assertion is presence-shaped (the IR carries
// no authored messages), fills go by label, and the specs are the
// component's regeneration UNIT: both files carry the same yours-now
// header and regenerate together.

export type TestRunner = "vitest" | "jest" | "playwright";

export type ComponentSpecOptions = Readonly<{
  runner: "vitest" | "jest";
  formName: string;
  schemaImport: SchemaImport;
  ir: FieldSpec;
  plan: GeneratedTestPlan;
  // Import specifier for the COMPONENT from the spec's location (the out
  // file's basename can differ from the form name).
  componentImport: string;
  // Import specifier for the app's render wrapper, as resolvable FROM THE
  // SPEC's location. Absent + kit output ⇒ the caller sets skipRender.
  renderWrapper?: string;
  // Emit the render-layer cases as it.skip (kit output with no wrapper
  // configured, or --form-prop components the spec cannot construct).
  skipRender: boolean;
  // The reason line for skipped render cases — goes in the comment.
  skipRenderReason?: string;
  // The zod-mode async probe tripped: submit cases emit it.skip with the
  // stub seam named, and field cases await an explicit validation pass.
  asyncSchema: boolean;
  // Options-prop overrides the component requires (each becomes an empty
  // readonly list in the render).
  optionsProps: readonly string[];
}>;

const HEADER =
  "// Generated by formstand-cli — edit freely, this file is yours.\n" +
  "// It regenerates WITH the component: the two are one unit, and the\n" +
  "// fills go by label, so a hand-renamed label fails here on purpose.";

const q = JSON.stringify;

// vitest imports its globals; jest provides them as real globals.
const globalsImport = (runner: "vitest" | "jest"): readonly string[] =>
  runner === "vitest"
    ? [`import { describe, expect, it } from "vitest";`]
    : [];

const itLine = (skip: boolean): string => (skip ? "it.skip" : "it");

export const emitComponentSpec = (
  options: ComponentSpecOptions,
): string => {
  const {
    runner,
    formName,
    schemaImport,
    ir,
    plan,
    renderWrapper,
    skipRender,
    asyncSchema,
    optionsProps,
  } = options;
  const schemaName = schemaImport.name;
  const schemaImportLine =
    schemaImport.kind === "default"
      ? `import ${schemaName} from ${q(schemaImport.from)};`
      : `import { ${schemaName} } from ${q(schemaImport.from)};`;
  const blankCast = blankNeedsCast(ir);
  const renderAttrs = optionsProps
    .map((name) => ` ${name}={[]}`)
    .join("");
  const submitSkip = asyncSchema;
  const blankInvalidPaths = [...plan.requiredPaths, ...plan.arrayMinPaths];
  const hasBlankInvalid = blankInvalidPaths.length > 0;

  // One rejecting/passing probe at a path: the format and bound cases
  // share the shape, differing only in the title and the literals (format
  // samples are strings; bound samples are already source text so a
  // number field gets a number).
  const probeCase = (
    title: string,
    path: string,
    bad: string,
    good: string,
  ): readonly string[] => [
    "",
    `  ${itLine(false)}(${q(title)}, async () => {`,
    "    const form = makeForm();",
    ...(asyncSchema
      ? [
          `    fillField(form, ${q(path)}, ${bad});`,
          `    await form.validateFieldsAsync([${q(path)}]);`,
        ]
      : [`    fillAndBlurField(form, ${q(path)}, ${bad});`]),
    `    expect(form.getState().errors[${q(path)}]).toBeDefined();`,
    ...(asyncSchema
      ? [
          `    fillField(form, ${q(path)}, ${good});`,
          `    await form.validateFieldsAsync([${q(path)}]);`,
        ]
      : [`    fillAndBlurField(form, ${q(path)}, ${good});`]),
    `    expect(form.getState().errors[${q(path)}]).toBeUndefined();`,
    "  });",
  ];

  const storeCases: readonly string[] = [
    ...(hasBlankInvalid
      ? [
          ...(submitSkip
            ? [
                "  // The schema parses asynchronously (an async refine): stub its",
                "  // IO (msw, a DI seam), then delete the .skip — the case is",
                "  // fully written and runs as-is once the network is faked.",
              ]
            : []),
          `  ${itLine(submitSkip)}("a blank submit reports the fields a blank form cannot satisfy", async () => {`,
          "    const form = makeForm();",
          "    const result = await submitForm(form);",
          `    expect(result.kind).toBe("invalid");`,
          `    if (result.kind === "invalid") {`,
          ...blankInvalidPaths.map(
            (entry) =>
              `      expect(result.errors[${q(entry.path)}]).toBeDefined();`,
          ),
          "    }",
          "  });",
          "",
        ]
      : []),
    ...(submitSkip
      ? [
          "  // Async schema: see the stub note above.",
        ]
      : []),
    `  ${itLine(submitSkip)}("filled with valid values, submit resolves the parsed payload", async () => {`,
    "    const form = makeForm();",
    "    form.setValues(validValues);",
    "    const result = await submitForm(form);",
    `    expect(result.kind).toBe("valid");`,
    `    if (result.kind === "valid") {`,
    ...(submitSkip
      ? [`      expect(result.data).toBeDefined();`]
      : [
          `      expect(result.data).toEqual(${schemaName}.parse(validValues));`,
        ]),
    "    }",
    "  });",
    ...plan.formatChecks.flatMap((check) =>
      probeCase(
        `${check.label} rejects a value that is not a valid ${check.format}`,
        check.path,
        q(check.bad),
        q(check.good),
      ),
    ),
    ...plan.boundChecks.flatMap((check) =>
      probeCase(
        `${check.label} rejects a value ${check.reason}`,
        check.path,
        check.bad,
        check.good,
      ),
    ),
  ];

  const renderNeeded =
    plan.firstInvalidLabel !== undefined || plan.formatChecks.length > 0;
  const renderCases: readonly string[] = !renderNeeded
    ? []
    : [
        "",
        `describe(${q(`${formName} — wiring (render)`)}, () => {`,
        ...(skipRender && options.skipRenderReason !== undefined
          ? [`  // ${options.skipRenderReason}`]
          : []),
        `  const renderForm = () =>`,
        renderWrapper === undefined
          ? `    render(<${formName}${renderAttrs} />);`
          : `    render(<${formName}${renderAttrs} />, { wrapper: RenderWrapper });`,
        "",
        ...(plan.firstInvalidLabel === undefined
          ? []
          : [
              `  ${itLine(skipRender)}("a blank submit marks the first blank-invalid control", async () => {`,
              "    renderForm();",
              `    fireEvent.click(screen.getByRole("button", { name: /submit/i }));`,
              `    await waitFor(() => {`,
              `      expect(`,
              `        screen.getByLabelText(${q(plan.firstInvalidLabel)}).getAttribute("aria-invalid"),`,
              `      ).toBe("true");`,
              "    });",
              "  });",
            ]),
        ...plan.formatChecks.slice(0, 1).flatMap((check) => [
          "",
          `  ${itLine(skipRender)}("a rejected value reaches the control's error wiring", async () => {`,
          "    renderForm();",
          `    const control = screen.getByLabelText(${q(check.label)});`,
          `    fireEvent.change(control, { target: { value: ${q(check.bad)} } });`,
          "    fireEvent.blur(control);",
          `    await waitFor(() => {`,
          `      expect(control.getAttribute("aria-invalid")).toBe("true");`,
          "    });",
          "  });",
        ]),
        "});",
      ];

  const hasProbes =
    plan.formatChecks.length > 0 || plan.boundChecks.length > 0;
  const needsFillField = asyncSchema && hasProbes;
  const needsFillAndBlur = !asyncSchema && hasProbes;
  const testingImports = [
    ...(needsFillAndBlur ? ["fillAndBlurField"] : []),
    ...(needsFillField ? ["fillField"] : []),
    "submitForm",
  ];

  return [
    HEADER,
    ...globalsImport(runner),
    ...(renderNeeded
      ? [`import { fireEvent, render, screen, waitFor } from "@testing-library/react";`]
      : []),
    `import { createForm } from "formstand";`,
    `import { ${testingImports.join(", ")} } from "formstand/testing";`,
    `import type { z } from "zod";`,
    schemaImportLine,
    `import { ${formName} } from ${q(options.componentImport)};`,
    ...(renderWrapper === undefined
      ? []
      : [`import { RenderWrapper } from ${q(renderWrapper)};`]),
    "",
    `type FormValues = z.input<typeof ${schemaName}>;`,
    "",
    blankCast
      ? `const blankValues = ${emitInitialValues(ir, 0)} as unknown as FormValues;`
      : `const blankValues: FormValues = ${emitInitialValues(ir, 0)};`,
    "",
    `const validValues = ${plan.validValues} as unknown as FormValues;`,
    "",
    `const makeForm = () => createForm(${schemaName}, { initialValues: blankValues });`,
    "",
    `describe(${q(`${formName} — validation (store-level)`)}, () => {`,
    ...storeCases,
    "});",
    ...renderCases,
    "",
  ].join("\n");
};

export type PlaywrightSpecOptions = Readonly<{
  formName: string;
  plan: GeneratedTestPlan;
  baseURL: string;
  route: string;
}>;

// The browser spec: navigate, drive by role and label, assert the
// aria-invalid wiring — v1 scope is native-control output (plain,
// shadcn); kit widget sequences are deliberately not emitted (design
// decision 3).
export const emitPlaywrightSpec = (
  options: PlaywrightSpecOptions,
): string => {
  const { formName, plan, baseURL, route } = options;
  return [
    HEADER,
    `import { expect, test } from "@playwright/test";`,
    "",
    `test.use({ baseURL: ${q(baseURL)} });`,
    "",
    ...(plan.firstInvalidLabel === undefined
      ? []
      : [
          `test(${q(`${formName}: a blank submit flags the first blank-invalid control`)}, async ({ page }) => {`,
          `  await page.goto(${q(route)});`,
          `  await page.getByRole("button", { name: /submit/i }).click();`,
          `  await expect(page.getByLabel(${q(plan.firstInvalidLabel)})).toHaveAttribute(`,
          `    "aria-invalid",`,
          `    "true",`,
          "  );",
          "});",
          "",
        ]),
    ...(plan.labelFills.length === 0
      ? []
      : [
          `test(${q(`${formName}: fills by label and submits without flagging them`)}, async ({ page }) => {`,
          `  await page.goto(${q(route)});`,
          ...plan.labelFills.map(
            (fill) =>
              `  await page.getByLabel(${q(fill.label)}).fill(${q(fill.text)});`,
          ),
          `  await page.getByRole("button", { name: /submit/i }).click();`,
          ...plan.labelFills.map(
            (fill) =>
              `  await expect(page.getByLabel(${q(fill.label)})).not.toHaveAttribute(\n    "aria-invalid",\n    "true",\n  );`,
          ),
          "});",
          "",
        ]),
  ].join("\n");
};
